### ISSUE TITLE
Bug in settings.py: AttributeError: 'module' object has no attribute ENABLE_PUSH

### ISSUE THREAD

**Issue by iteras** [python-hyper/hyper-h2#1050]
h2 updated from h2.settings.ENABLE_PUSH to h2.settings.SettingCodes.ENABLE_PUSH.

Please replace /hyper/http20/connection.py:411 with:
 {h2.settings.SettingCodes.ENABLE_PUSH: int(self._enable_push)}

**Comment by Lukasa** [comment]
The 2.4 series is not still supported, so that bump sounds reasonable to me.

**Comment by aladagemre** [comment]
Any updates on this?

**Comment by pgjones** [comment]
Hi @aladagemre, I think this is better asked on the hyper tracker, however I think you should take a look at [httpx](https://github.com/encode/httpx) as I believe it to be the [successor](https://github.com/python-hyper/hyper/issues/415) to hyper.

(As I don't think this is a h2 issue, I'll close. Please reopen if you think otherwise).
