### ISSUE TITLE
Consider having received headers be bytes, not unicode strings.

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyper-h2#154]
Currently the `RequestReceived`, `ResponseReceived`, and `TrailersReceived` events all return the headers as a list of tuples of unicode strings. This happens because HPACK decodes the headers as UTF-8 before use. While this is enormously convenient when it works, which is almost all the time, it introduces the risk that a senseless HTTP/2 implementation may send non-UTF-8-encoded data and have hyper-h2 barf on it.

For the 2.x series we're stuck with this design decision, but when we come to look at doing a 3.0.0 we may want to revisit this decision.

**Comment by Kriechi** [comment]
I think this is fully covered in #198 - and the only remaining thing to discuss/decide is to change the default encoding from `utf-8` to *no encoding* in a 3.0 release.

Personally I have no strong opinion, since changing it is a simple flag on the connection. However I'm slightly leaning toward going raw bytes-only for all internals, just so API users need to think about what they expect to get and what they actually want.

**Comment by Lukasa** [comment]
Agreed, this issue is basically whether or not we change the default. I remain +1 on changing the default: I think unicode-by-default was the wrong choice, though it seemed sensible back when I first made that call in 2014.
