### ISSUE TITLE
curio example fails on large files

### ISSUE THREAD

**Issue by kdart** [python-hyper/hyper-h2#177]
Hello, I'm trying to write a small http/2 server using curio, based on the example found here. I'm just trying out the example. It works fine for small files, but when I try to transfer large files in throws an exception, and the client stalls. 
```
File "/Volumes/USER/Users/keith_dart/opensrc/hyper-h2/h2/connection.py", line 570, in send_data
    (len(data), self.local_flow_control_window(stream_id))
h2.exceptions.FlowControlError: Cannot send 8192 bytes, flow control window is 8191.
```

I'm wondering if anyone else has seen this yet?  I'm still trying to figure out where the problem is.

**Comment by Lukasa** [comment]
@kdart Do you mind pasting the complete traceback?

**Comment by Lukasa** [comment]
Heh, nevermind, I can see the bug in the example. In fact I can see two: one is much less likely but much more subtle, whereas one is egregious.

The first is that the curio example incorrectly uses [`remote_flow_control_window`](http://python-hyper.org/h2/en/latest/api.html#h2.connection.H2Connection.remote_flow_control_window) where it should [`local_flow_control_window`](http://python-hyper.org/h2/en/latest/api.html#h2.connection.H2Connection.local_flow_control_window). Making that simple change should resolve your problem (and if you'd like to make a pull request fixing that problem I'd happily merge it).

The bigger problem is that the curio example yields the flow of control *after* determining how much data to send, in order to read data from the file. That potentially can cause the size of the flow control window to change, causing the curio example to violate the flow control constraints.

Solving that is a bit tricky, but essentially requires keeping an in-memory buffer of file data. I'll take a look at tweaking that soon.

**Comment by kdart** [comment]
OK, Thanks. BTW, I'm also running a slightly modified version of the because the example, as-is, won't even start.

```
listening on :8080
Curio: Task Crash: h2_server
Traceback (most recent call last):
  File "/Volumes/USER/Users/keith_dart/opensrc/curio/curio/kernel.py", line 386, in run
    op, *args = current.coro.send(current.next_value)
  File "curio-server.py", line 52, in h2_server
    with sock:
  File "/Volumes/USER/Users/keith_dart/opensrc/curio/curio/io.py", line 262, in __enter__
    raise RuntimeError('Use async-with for context management')
RuntimeError: Use async-with for context management
```

So making that small tweak as that suggests is also necessary.

**Comment by Lukasa** [comment]
@kdart Heh, that's the downside of having an example that relies on a rapidly-changing framework. Again, if you're feeling up to it I'd be happy to merge a pull request that makes those two tweaks.

**Comment by kdart** [comment]
OK, stay tuned.

**Comment by kdart** [comment]
#178 addresses this.

**Comment by kdart** [comment]
Works now.

**Comment by ramc88** [comment]
Hi, i'm having the same problem but using hyper (not hyper-h2) but at the client side, i can't receive files bigger than 64k even changing the "network_buffer_size" which i think it's the problem, it's setting in 64k by default, here i put some of my code:


conn = hyper.HTTP20Connection(SERVER, sys.argv[2], True, window_manager=None, enable_push=False, ssl_context=ssl_context)
conn.network_buffer_size = 900000
conn.connect()
resp = conn.get_response()
arch = resp.read()

**Comment by Lukasa** [comment]
@ramc88 You can't receive files bigger than 64k? Are you sure that that's what's going on? What's the symptom of the problem?
