### ISSUE TITLE
Flow control issues in the curio example server

### ISSUE THREAD

**Issue by njsmith** [python-hyper/hyper-h2#253]
(By "flow control" here I mean coordinating on reading/writing to a socket, *not* HTTP/2 flow control. I don't know another term for this?)

1) The code calls `sock.sendall` from multiple parallel tasks. This is bad, because `sendall` is not an atomic operation, so the writes could get intermixed on the wire. There needs to be one linearization point where data read out of `data_to_send()` is queued to go out on the wire.

2) The receive loop (the `H2Server.run` method) alternates between reading and blocking on sending. This seems like risky behavior, because it creates the possibility of deadlock: if a client was written in a similar fashion, then one could potentially end up in a situation where they were both blocked in `sendall`, waiting for the other to call `recv`.

I don't know how to handle these properly in the HTTP/2 context, especially when combined with HTTP/2 flow control (which I don't understand at all yet :-)), and the requirement to not allocate infinite memory for buffers (so we can't just keep calling `recv` forever without any backpressure, or queuing up unbounded amounts of data to send). I'm... not actually entirely sure that (2) even is solvable given bounded memory use, actually?

**Comment by rbtcollins** [comment]
Concurrency issues, or data races, or thread safety, if you are looking for
a label

**Comment by Lukasa** [comment]
Both of these things are very solveable, and HTTP/2 flow control plays into both.

Firstly, part 1). The code cannot call `sendall` from parallel threads (real or virtual) unless there is a lock around the call. This is a hard-and-fast rule that cannot be broken: if you do it then your code is bugged. *However*, this is also true of any code that calls `send` from parallel threads: given that `send` can send *part* of the data, the apparent atomicity of `send` isn't helpful: you can still mix your writes badly.

In fact, this rule is *more generally* applicable. I has little to do with HTTP/2 and everything to do with concurrent socket programming: if you're using a TCP socket then you *must not* write from multiple threads without obtaining a lock to serialize that access. Even then it's frequently better to adopt a model that says that you have one thread that "owns" sending from a socket, which loops around pulling messages from a queue and sending them on the socket.

As to 2), this is generally not a good idea. Your sending loop should ideally not get stuck in blocking operations: it should instead be using `select` or something like it to confirm that an operation is possible, and then doing it. That allows you to avoid using `sendall`, which absolutely can get stuck, and so you can free yourself up to `recv` as needed.

So how does HTTP/2 flow control mix into this? It does so in two places. Firstly, on the receive side: if you manage your HTTP/2 flow control appropriately it is not possible to build up unbounded buffers of data. Specifically, you shouldn't open HTTP/2 flow control windows for the stream until the data has been removed from your receive buffer and passed to your application (that is, until it's semantically no longer buffered). You can see this in the [Twisted server](https://github.com/twisted/twisted/blob/trunk/twisted/web/_http2.py#L849), which will immediately reopen the flow control window if it passes the data to the application but otherwise keeps hold of it until it's unbuffered later.

The advantage of this is that it limits what the remote peer can send you. In the Twisted case, we cannot buffer more than one connection flow control window of data. That's probably too small, so I'm going to consider adjusting the Twisted code to allow bigger buffers, but it'll be no more than SETTINGS_MAX_CONCURRENT_STREAMS * SETTINGS_INITIAL_WINDOW_SIZE bytes. That means that if your application is not consuming data, eventually the remote peer is unable to send you any more.

For queueing up data to send, you need to be able to signal flow control messages from the *remote* connection. Essentially, you need a way to say to a task that wants to send a HTTP/2 data frame: "sorry, you're blocked by flow control, I'll tell you when you're unblocked and you can send again". That once again bounds how much data you can buffer by the HTTP/2 flow control window, this time the window of the peer. Twisted's HTTP/2 server does this as well.
