### ISSUE TITLE
no way to detect "true" stream close

### ISSUE THREAD

**Issue by ruz** [python-hyper/hyper-h2#544]
Hi,
StreamEnded event may be fired before stream is actually closed

Here is a situation. Client sends POST request with data, however server responds right after receiving headers and ends the stream before all data is sent. Stream states and frames:

* open
* ->headers
* <-headers and data+end_stream flag
* half_closed_remote + StreamEnded event
* ->data+end_stream flag
* closed

There is no way to detect the final transition to closed state as this transition is handled by H2StreamStateMachine.send_end_stream that doesn't emit any events.

This behaviour is even documented:

> The stream may not be fully closed if it has not been closed locally, but no further data or headers should be expected on that stream.

If I can not detect "fully closed" streams then I don't have hook to check whether I have pending requests or not. What result either in hang requests or in TooManyStreamsError exception.

**Comment by Lukasa** [comment]
Thanks for opening this report!

So, it's not clear to me exactly what you're looking for. `StreamEnded` is specifically a report that the remote peer has closed its half of the stream. When you've received that, and called `end_stream`, then the stream is fully complete. Otherwise, it is only partially complete. 

What I don't quite follow is what change specifically you'd like to see.

**Comment by ruz** [comment]
An event that says "StreamClosed" from both ends, so opening a new stream wouldn't result TooManyStreamsError. Without such event I would have to partially re-implement streams' state machine in my code.

**Comment by ruz** [comment]
May be I was not clear, but at the moment I receive end_stream from the server I still have data queued up to be pushed into the stream. The server just analyzes headers and responds with an error. May be I should stop sending data and just send end_stream frame from my end. However, I can imagine theoretical situation when a server responds earlier and still expected to consume the rest of the data client has for him.

**Comment by Lukasa** [comment]
Yes, that can definitely happen, but the client has to decide what to do in the face of an early response from the server. 

In your situation, which function would emit the event? Right now hyper-h2 only emits events from `receive_data`: you sending `end_stream` is not an event returning function. So when should you see this event?

**Comment by ruz** [comment]
Forgot that events are not callbacks based. It's inherited codebase I'm working on. Hoped to find easy to implement solution. Looks like I stuck with a hard one.

Anyway, I'm quite surprised that streams' state changes are not mapped directly onto events. I believe it would be very handy and less unpredictable (since described by HTTP/2 spec itself). Feel free to close.

**Comment by Lukasa** [comment]
So the goal of h2 is to try to abstract away some of the specific HTTP/2 stage changes from being specifically events. This is primarily because they are not a *sufficient* set of events (e.g. PRIORITY frames never cause state changes), and so if we try to translate events into what their *semantic* effect is, rather than their specific state transitions. 

The core design decision causing you trouble, I think, is that we only emit events for things the remote peer did: we assume you're keeping track of the events you trigger. We may need a way to improve that.
